version: '3.9'
services:
  backend:
    build: ./backend
    env_file:
      - .env.production
    environment:
      - BASE_URL=${BASE_URL}
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    env_file:
      - ./frontend/.env.local.production
    ports:
      - "3000:3000"
    depends_on:
      - backend

